### ISSUE TITLE
Code breaks in newer version of electron and create-electron-app

### ISSUE THREAD

**Issue by Assassinduck** [fireship-io/223-electron-screen-recorder#6]
In the newest version of electron and electron forge, the code breaks. If you create a new fresh create-electron-app project and put the code from the repo into the project, the console spits out "Uncaught TypeError: Cannot destructure property 'dialog' of 'remote' as it is undefined. at render.js:5"

**Comment by leslie-alldridge** [comment]
same here, did you find a fix?

**Comment by leslie-alldridge** [comment]
@Assassinduck you just need to enable remote modules for your app (it's not enabled by default any more)
```
const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      enableRemoteModule: true,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadFile(path.join(__dirname, 'index.html'));

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};
```

**Comment by Vimal-N** [comment]
> @Assassinduck you just need to enable remote modules for your app (it's not enabled by default any more)
> 
> ```
> const createWindow = () => {
>   // Create the browser window.
>   const mainWindow = new BrowserWindow({
>     width: 800,
>     height: 600,
>     webPreferences: {
>       nodeIntegration: true,
>       enableRemoteModule: true,
>     },
>   });
> 
>   // and load the index.html of the app.
>   mainWindow.loadFile(path.join(__dirname, 'index.html'));
> 
>   // Open the DevTools.
>   mainWindow.webContents.openDevTools();
> };
> ```

this worked, thanks!!!!!!!!!!!!!!!!!!!!! :boom:

**Comment by Assassinduck** [comment]
Thank you so much, that worked.
